name: CI
on: workflow_dispatch
jobs:
  build:
    name: Build & test
    strategy:
      matrix:
        include:
          - platform: linux
            arch: x64
            os: "ubuntu-22.04"
          - platform: linux
            arch: arm64
            os: "ubuntu-24.04-arm"
          - platform: windows
            arch: x64
            os: "windows-2022"
          - platform: mac
            arch: x64
            os: "macos-15-intel"
          - platform: mac
            arch: arm64
            os: "macos-14"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          check-latest: true
          cache: 'npm'

      # Due to https://github.com/electron-userland/electron-builder/issues/3901
      # Electron-Builder fails to produce deb packages on arm64 without this:
      - name: Install system FPM to fix ARM64 Linux builds
        if: matrix.platform == 'linux' && matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - run: npm ci

      # The API key in APPLE_API_KEY is a PEM cert that must be read from disk:
      - name: Prepare Apple API key
        run: echo "$APPLE_API_KEY" > ./apple-api-key.p8
        if: github.event_name == 'push' && startsWith(matrix.os, 'macos-')
        env:
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}

      - name: Run unsigned build
        if: github.event_name != 'push'
        run: npm run build
        env:
          ENABLE_SIGNING: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_SYSTEM_FPM: ${{ matrix.platform == 'linux' && matrix.arch == 'arm64' }}

      - name: Run smoke tests
        run: |
          # We manually start ADB, so the tests don't (because if they do, they fail
          # to exit, due to the hanging process)
          "$ANDROID_HOME/platform-tools/adb" start-server 2>/dev/null || true

          if [ "$RUNNER_OS" == "Linux" ]; then
            xvfb-run --auto-servernum npm test
          else
            npm test
          fi
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}-distributables
          path: dist/HttpToolkit-*
          if-no-files-found: error
  publish:
    name: Publish a release
    runs-on: "ubuntu-22.04"
    needs: build
    permissions:
      contents: write
    steps:
      - name: Get all distributables
        uses: actions/download-artifact@v4

      - name: Normalize arch names to x64 or arm64
        run: |
          find . -maxdepth 2 -type f -name "*" | while read -r file; do
            filename=$(basename "$file")
            newname=$(echo "$filename" | sed -e 's/amd64/x64/g' -e 's/x86_64/x64/g' -e 's/aarch64/arm64/g')
            if [ "$filename" != "$newname" ]; then
              mv -v "$file" "$newname"
            fi
          done
      - name: Remove blockmap file
        run: rm ./*/*.blockmap

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: aarzaary/app
          repo_token: ${{ secrets.personal_token }}
          file: ./*/*
          tag: ${{ env.SHA }}
          body: "App Release"
          file_glob: true
          overwrite: true
          make_latest: true